### ISSUE TITLE
[BetterMediaViewer] Crash issue caused by 2 things

### ISSUE THREAD

**Issue by K4dzu** [zt64/aliucord-plugins#31]
If you start multiple downloads and one finishes while others are downloading, aliucord crashes
Another case is when you are watching a video while you started a download, if the download finishes while you are watching the video, aliucord crashes
Sending 2 crashlogs for the respective crashes

`java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.DOWNLOAD_COMPLETE flg=0x10 pkg=com.aliucord (has extras) } in com.aliucord.plugins.bettermediaviewer.Patches$patchWidget$1$1$1$1$receiver$1@e007031
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1590)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7864)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
Caused by: java.lang.IllegalArgumentException: Receiver not registered: com.aliucord.plugins.bettermediaviewer.Patches$patchWidget$1$1$1$1$receiver$1@e007031
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1457)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1652)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:726)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:726)
	at com.aliucord.plugins.bettermediaviewer.Patches$patchWidget$1$1$1$1$receiver$1.onReceive(Patches.kt:64)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1580)
	... 8 more`

`java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.DOWNLOAD_COMPLETE flg=0x10 pkg=com.aliucord (has extras) } in com.aliucord.plugins.bettermediaviewer.Patches$patchWidget$1$1$1$1$receiver$1@3e48ae2
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1590)
	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:7864)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
Caused by: java.lang.IllegalArgumentException: Receiver not registered: com.aliucord.plugins.bettermediaviewer.Patches$patchWidget$1$1$1$1$receiver$1@3e48ae2
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1457)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1652)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:726)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:726)
	at com.aliucord.plugins.bettermediaviewer.Patches$patchWidget$1$1$1$1$receiver$1.onReceive(Patches.kt:64)
	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1580)
	... 8 more`

**Comment by K4dzu** [comment]
The  2nd case seems to not only extend to videos – it seems to also affect viewing any image in focus or whatever it's called
